/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;



/**
 *
 * @author laraashour
 */

import customer.Customer;
import customer.CustomerAPI;
import customer.CustomerAPI_Impl;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import database.DBConnection;
import merchant.SA_Merchant_API_Impl;
import java.sql.Connection;

public class Customers extends javax.swing.JPanel {
    
    private String userRole;
    private final CustomerAPI customerAPI = new CustomerAPI_Impl();
    private SA_Merchant_API_Impl merchantAPI; 

    /**
     * Creates new form Customers
     */
public Customers() {
    initComponents();
    
    jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        filterCustomers();
    }
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        filterCustomers();
    }
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        filterCustomers();
    }
});
    
    Connection conn = DBConnection.getConnection();
    merchantAPI = new SA_Merchant_API_Impl(conn);

try {
    customerAPI.normaliseStatuses();
    merchantAPI.checkAndAutoUpdateAllAccounts();
} catch (Exception e) {
    JOptionPane.showMessageDialog(this,
        "Error updating statuses: " + e.getMessage());
}

    loadCustomersTable();
}



public Customers(String role) {
    initComponents();
    
    jTextField1.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {
    public void insertUpdate(javax.swing.event.DocumentEvent e) {
        filterCustomers();
    }
    public void removeUpdate(javax.swing.event.DocumentEvent e) {
        filterCustomers();
    }
    public void changedUpdate(javax.swing.event.DocumentEvent e) {
        filterCustomers();
    }
});
    
    this.userRole = role;
    Connection conn = DBConnection.getConnection();
    merchantAPI = new SA_Merchant_API_Impl(conn);

    try {
        customerAPI.normaliseStatuses();
        merchantAPI.checkAndAutoUpdateAllAccounts();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error normalising statuses: " + e.getMessage());
    }


    loadCustomersTable();
}
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerJpanel2 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 853));

        CustomerJpanel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        CustomerJpanel2.setForeground(new java.awt.Color(102, 102, 102));
        CustomerJpanel2.setText("Manage customer accounts and credit");

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Customer Management");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel3.setText("Customer Accounts");

        jTextField1.setText("Search by name, account number, or email...");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Search:");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account #", "Name", "Email", "Phone", "Credit Limit", "Status", "Outstanding Balance", "Discount Plan"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+ Add Customer");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("- Remove Customer");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update Credit Limit");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton6.setBackground(new java.awt.Color(0, 0, 51));
        jButton6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Record Payment");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton5.setBackground(new java.awt.Color(0, 0, 51));
        jButton5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Set Discount Plan");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton7.setBackground(new java.awt.Color(0, 0, 51));
        jButton7.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Modify Discount Plan");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton8.setBackground(new java.awt.Color(0, 0, 51));
        jButton8.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Delete Discount Plan");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Reactivate Account");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton9.setBackground(new java.awt.Color(0, 0, 51));
        jButton9.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Generate Reminders");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(628, 628, 628)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(684, 684, 684)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(469, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 662, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(CustomerJpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CustomerJpanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
         filterCustomers();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                                    
    javax.swing.JTextField txtName = new javax.swing.JTextField();
    javax.swing.JTextField txtDob = new javax.swing.JTextField();
    javax.swing.JTextField txtEmail = new javax.swing.JTextField();
    javax.swing.JTextField txtPhone = new javax.swing.JTextField();
    javax.swing.JTextField txtHouseNumber = new javax.swing.JTextField();
    javax.swing.JTextField txtPostcode = new javax.swing.JTextField();
    javax.swing.JTextField txtCreditLimit = new javax.swing.JTextField();

    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));
    panel.add(new javax.swing.JLabel("Name:"));
    panel.add(txtName);
    panel.add(new javax.swing.JLabel("Date of Birth (YYYY-MM-DD):"));
    panel.add(txtDob);
    panel.add(new javax.swing.JLabel("Email:"));
    panel.add(txtEmail);
    panel.add(new javax.swing.JLabel("Phone:"));
    panel.add(txtPhone);
    panel.add(new javax.swing.JLabel("House Number:"));
    panel.add(txtHouseNumber);
    panel.add(new javax.swing.JLabel("Postcode:"));
    panel.add(txtPostcode);
    panel.add(new javax.swing.JLabel("Credit Limit:"));
    panel.add(txtCreditLimit);

    int result = javax.swing.JOptionPane.showConfirmDialog(
        this,
        panel,
        "Add Customer",
        javax.swing.JOptionPane.OK_CANCEL_OPTION,
        javax.swing.JOptionPane.PLAIN_MESSAGE
    );

    if (result == javax.swing.JOptionPane.OK_OPTION) {
        String name = txtName.getText().trim();
        String dob = txtDob.getText().trim();
        String email = txtEmail.getText().trim();
        String phone = txtPhone.getText().trim();
        String houseNumberText = txtHouseNumber.getText().trim();
        String postcode = txtPostcode.getText().trim();
        String creditLimitText = txtCreditLimit.getText().trim();

        // Empty validation
        if (name.isEmpty() || dob.isEmpty() || email.isEmpty() || phone.isEmpty()
                || houseNumberText.isEmpty() || postcode.isEmpty() || creditLimitText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        // Name validation
        if (!name.matches("[A-Za-z ]{2,}")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid customer name.");
            return;
        }

        // DOB validation
        if (!dob.matches("\\d{4}-\\d{2}-\\d{2}")) {
            JOptionPane.showMessageDialog(this, "DOB must be in format YYYY-MM-DD.");
            return;
        }

        // Email validation
        if (!email.matches("^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+$")) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.");
            return;
        }

        // Phone validation
        if (!phone.matches("\\d{10,11}")) {
            JOptionPane.showMessageDialog(this, "Phone number must contain 10 to 11 digits.");
            return;
        }

        // House number validation
        int houseNumber;
        try {
            houseNumber = Integer.parseInt(houseNumberText);
            if (houseNumber <= 0) {
                JOptionPane.showMessageDialog(this, "House number must be greater than 0.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "House number must be a valid number.");
            return;
        }

        // Postcode validation
        if (postcode.length() < 4) {
            JOptionPane.showMessageDialog(this, "Please enter a valid postcode.");
            return;
        }

        // Credit limit validation
        double creditLimit;
        try {
            creditLimit = Double.parseDouble(creditLimitText);
            if (creditLimit < 0) {
                JOptionPane.showMessageDialog(this, "Credit limit must be 0 or greater.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for credit limit.");
            return;
        }

        // Split name
        String[] parts = name.split("\\s+", 2);
        String firstName = parts[0];
        String surname = parts.length > 1 ? parts[1] : "";

        try {
            boolean added = customerAPI.addCustomer(
                firstName,
                surname,
                dob,
                email,
                phone,
                houseNumber,
                postcode,
                creditLimit
            );

            if (added) {
                JOptionPane.showMessageDialog(this, "Customer added successfully.");
                loadCustomersTable();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add customer.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a customer account to delete.");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this customer account?",
            "Confirm Delete",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            String accountId = jTable1.getValueAt(selectedRow, 0).toString();

            try {
                boolean deleted = customerAPI.deleteCustomer(accountId);

                if (deleted) {
                    JOptionPane.showMessageDialog(this, "Customer account deleted successfully.");
                    loadCustomersTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to delete customer account.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a customer first.");
        return;
    }

    String accountId = jTable1.getValueAt(selectedRow, 0).toString();

    String newLimit = JOptionPane.showInputDialog(this, "Enter new credit limit:");

    if (newLimit == null) {
        return;
    }

    newLimit = newLimit.trim();

    if (newLimit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Credit limit cannot be empty.");
        return;
    }

    double creditLimit;
    try {
        creditLimit = Double.parseDouble(newLimit);
        if (creditLimit < 0) {
            JOptionPane.showMessageDialog(this, "Credit limit must be 0 or greater.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid number.");
        return;
    }

    try {
        int customerId = Integer.parseInt(accountId.substring(3));
        boolean updated = merchantAPI.setCreditLimit(customerId, creditLimit);

        if (updated) {
            JOptionPane.showMessageDialog(this, "Credit limit updated successfully.");
            merchantAPI.checkAndAutoUpdateAllAccounts();
            loadCustomersTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update credit limit.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
            if (userRole == null || !userRole.equalsIgnoreCase("Manager")) {
        JOptionPane.showMessageDialog(this,
            "Access denied. Only managers can reactivate accounts.");
        return;
    }

    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this,
            "Please select a customer first.");
        return;
    }

    String status = jTable1.getValueAt(selectedRow, 5).toString();

    if (!status.equalsIgnoreCase("IN_DEFAULT")) {
        JOptionPane.showMessageDialog(this,
            "Only accounts in IN_DEFAULT can be reactivated.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to reactivate this account?",
        "Confirm Reactivation",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        String accountId = jTable1.getValueAt(selectedRow, 0).toString();
        int customerId = Integer.parseInt(accountId.substring(3));

        boolean updated = merchantAPI.managerReactivateAccount(customerId);

        if (updated) {
            JOptionPane.showMessageDialog(this,
                "Account reactivated successfully.");
            merchantAPI.checkAndAutoUpdateAllAccounts();
            loadCustomersTable();
        } else {
            JOptionPane.showMessageDialog(this,
                "Failed to reactivate account.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a customer first.");
        return;
    }

    String accountId = jTable1.getValueAt(selectedRow, 0).toString();

    String[] planOptions = {"FIXED", "FLEXIBLE"};
    String planType = (String) JOptionPane.showInputDialog(
        this,
        "Select discount plan type:",
        "Set Discount Plan",
        JOptionPane.PLAIN_MESSAGE,
        null,
        planOptions,
        planOptions[0]
    );

    if (planType == null) {
        return;
    }

    String discountText = JOptionPane.showInputDialog(
        this,
        "Enter discount value (%):"
    );

    if (discountText == null) {
        return;
    }

    discountText = discountText.trim();

    if (discountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Discount value cannot be empty.");
        return;
    }

    double discountValue;
    try {
        discountValue = Double.parseDouble(discountText);

        if (discountValue < 0) {
            JOptionPane.showMessageDialog(this, "Discount value must be 0 or greater.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid discount value.");
        return;
    }

    try {
        boolean success = customerAPI.setDiscountPlan(accountId, planType, discountValue);

        if (success) {
            JOptionPane.showMessageDialog(this, "Discount plan set successfully.");
            loadCustomersTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to set discount plan.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a customer first.");
        return;
    }

    String accountId = jTable1.getValueAt(selectedRow, 0).toString();
    String amountText = JOptionPane.showInputDialog(this, "Enter payment amount:");

    if (amountText == null) {
        return;
    }

    amountText = amountText.trim();

    if (amountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Payment amount cannot be empty.");
        return;
    }

    double amount;
    try {
        amount = Double.parseDouble(amountText);

        if (amount <= 0) {
            JOptionPane.showMessageDialog(this, "Payment amount must be greater than 0.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid payment amount.");
        return;
    }

try {
    int customerId = Integer.parseInt(accountId.substring(3));

    boolean paid = merchantAPI.recordAccountPayment(customerId, amount);

    if (paid) {
        customerAPI.clearReminderStatusesIfPaid(accountId);
        merchantAPI.checkAndAutoUpdateAllAccounts();
        JOptionPane.showMessageDialog(this, "Payment recorded successfully.");
        loadCustomersTable();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to record payment.");
    }

} catch (Exception e) {
    JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a customer first.");
        return;
    }

    String accountId = jTable1.getValueAt(selectedRow, 0).toString();

    String[] planOptions = {"FIXED", "FLEXIBLE"};
    String planType = (String) JOptionPane.showInputDialog(
        this,
        "Select new discount plan type:",
        "Modify Discount Plan",
        JOptionPane.PLAIN_MESSAGE,
        null,
        planOptions,
        planOptions[0]
    );

    if (planType == null) {
        return;
    }

    String discountText = JOptionPane.showInputDialog(
        this,
        "Enter new discount value (%):"
    );

    if (discountText == null) {
        return;
    }

    discountText = discountText.trim();

    if (discountText.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Discount value cannot be empty.");
        return;
    }

    double discountValue;
    try {
        discountValue = Double.parseDouble(discountText);

        if (discountValue < 0) {
            JOptionPane.showMessageDialog(this, "Discount value must be 0 or greater.");
            return;
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid discount value.");
        return;
    }

    try {
        boolean success = customerAPI.modifyDiscountPlan(accountId, planType, discountValue);

        if (success) {
            JOptionPane.showMessageDialog(this, "Discount plan modified successfully.");
            loadCustomersTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to modify discount plan. Ensure customer has a discount plan.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
            int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a customer first.");
        return;
    }

    String accountId = jTable1.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this discount plan?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    try {
        boolean success = customerAPI.deleteDiscountPlan(accountId);

        if (success) {
            JOptionPane.showMessageDialog(this, "Discount plan deleted successfully.");
            loadCustomersTable();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to delete discount plan. Ensure customer has a discount plan.");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
            try {
        int generated = customerAPI.generateReminders();

        if (generated > 0) {
            JOptionPane.showMessageDialog(this,
                generated + " reminder(s) generated successfully.");
        } else {
            JOptionPane.showMessageDialog(this,
                "No reminders were due to be generated.");
        }

        loadCustomersTable();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error generating reminders: " + e.getMessage());
    }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void showReminderLetter(String customerName, String accountId, String balance) {
        String reminderText =
            "InfoPharma ORDERING SYSTEM STUDENT'S BRIEF\n\n"
            + "9.6 Appendix 6: Payment overdue Reminders\n\n"
            + "Client: " + customerName + "\n"
            + "3, High Level Drive,\n"
            + "Sydenham,\n"
            + "SE26 3ET\n"
            + "Phone: 0208 778 0124\n"
            + "Fax: 0208 778 0125\n\n"
            + "InfoPharma Ltd.,\n"
            + "19 High St.,\n"
            + "Ashford,\n"
            + "Kent\n\n"
            + "Dear Client,\n\n"
            + "REMINDER - INVOICE NO: 197362\n\n"
            + "IPOS Account: " + accountId + "            Total Amount: " + balance + "\n\n"
            + "According to our records, it appears that we have not yet received payment "
            + "of the above invoice, which was raised against " + customerName + ".\n\n"
            + "We would appreciate payment at your earliest convenience.\n\n"
            + "If you have already sent a payment to us recently, please accept our apologies.\n\n"
            + "Yours sincerely,\n\n"
            + "PharmaTech\n\n"
            + "------------------------------------------------------------\n\n"
            + "SECOND REMINDER - INVOICE NO: 197362\n\n"
            + "IPOS Account: " + accountId + "            Total Amount: " + balance + "\n\n"
            + "It appears that we still have not yet received payment of the above invoice "
            + "despite the earlier reminder.\n\n"
            + "We would appreciate it if you would settle this invoice in full by return.\n\n"
            + "If you have already sent a payment to us recently, please accept our apologies.\n\n"
            + "Yours sincerely,\n\n"
            + "PharmaTech";

        javax.swing.JTextArea textArea = new javax.swing.JTextArea(reminderText);
        textArea.setEditable(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setCaretPosition(0);
        textArea.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        textArea.setMargin(new java.awt.Insets(14, 14, 14, 14));

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
        scrollPane.setPreferredSize(new java.awt.Dimension(760, 620));

        JOptionPane.showMessageDialog(
            this,
            scrollPane,
            "Customer Payment Reminder",
            JOptionPane.PLAIN_MESSAGE
        );
    }

    private void loadCustomersTable() {
    try {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // clear table

        List<Customer> customers = customerAPI.getAllCustomers();

        for (Customer c : customers) {
            model.addRow(new Object[]{
                c.getAccountId(),
                c.getFirstName() + " " + c.getSurname(),
                c.getEmail(),
                c.getPhone(),
                c.getCreditLimit(),
                c.getAccountStatus(),
                c.getOutstandingBalance(),
                customerAPI.getDiscountPlan(c.getAccountId())
                
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error loading customers: " + e.getMessage());
    }
}
    
private void filterCustomers() {
    try {
        String searchText = jTextField1.getText().trim().toLowerCase();

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        List<Customer> customers = customerAPI.getAllCustomers();

        for (Customer c : customers) {
            String accountId = c.getAccountId().toLowerCase();
            String name = c.getFirstName().toLowerCase();
            String email = c.getEmail().toLowerCase();

            if (accountId.contains(searchText) ||
                name.contains(searchText) ||
                email.contains(searchText)) {

model.addRow(new Object[]{
    c.getAccountId(),
    c.getFirstName() + " " + c.getSurname(),
    c.getEmail(),
    c.getPhone(),
    c.getCreditLimit(),
    c.getAccountStatus(),
    c.getOutstandingBalance(),
    customerAPI.getDiscountPlan(c.getAccountId())
});
            }
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Search error: " + e.getMessage());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label CustomerJpanel2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
