/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author laraashour
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        stockPanel1 = new javax.swing.JPanel();
        lbStock1 = new javax.swing.JLabel();
        salesPanel2 = new javax.swing.JPanel();
        lbSales2 = new javax.swing.JLabel();
        pendingPanel4 = new javax.swing.JPanel();
        lbPending4 = new javax.swing.JLabel();
        accountPanel3 = new javax.swing.JPanel();
        lbAccount3 = new javax.swing.JLabel();
        lbTitle = new javax.swing.JLabel();
        lbInfo1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        stockPanel1.setBackground(new java.awt.Color(255, 255, 255));
        stockPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbStock1.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbStock1.setText("Total Stock Items");

        javax.swing.GroupLayout stockPanel1Layout = new javax.swing.GroupLayout(stockPanel1);
        stockPanel1.setLayout(stockPanel1Layout);
        stockPanel1Layout.setHorizontalGroup(
            stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanel1Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(lbStock1)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        stockPanel1Layout.setVerticalGroup(
            stockPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stockPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbStock1)
                .addContainerGap(261, Short.MAX_VALUE))
        );

        salesPanel2.setBackground(new java.awt.Color(255, 255, 255));
        salesPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbSales2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbSales2.setText("Today's Sales");

        javax.swing.GroupLayout salesPanel2Layout = new javax.swing.GroupLayout(salesPanel2);
        salesPanel2.setLayout(salesPanel2Layout);
        salesPanel2Layout.setHorizontalGroup(
            salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(lbSales2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        salesPanel2Layout.setVerticalGroup(
            salesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salesPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbSales2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pendingPanel4.setBackground(new java.awt.Color(255, 255, 255));
        pendingPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbPending4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbPending4.setText("Pending Orders");

        javax.swing.GroupLayout pendingPanel4Layout = new javax.swing.GroupLayout(pendingPanel4);
        pendingPanel4.setLayout(pendingPanel4Layout);
        pendingPanel4Layout.setHorizontalGroup(
            pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanel4Layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(lbPending4)
                .addContainerGap(146, Short.MAX_VALUE))
        );
        pendingPanel4Layout.setVerticalGroup(
            pendingPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbPending4)
                .addContainerGap(263, Short.MAX_VALUE))
        );

        accountPanel3.setBackground(new java.awt.Color(255, 255, 255));
        accountPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbAccount3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        lbAccount3.setText("Active Customers");

        javax.swing.GroupLayout accountPanel3Layout = new javax.swing.GroupLayout(accountPanel3);
        accountPanel3.setLayout(accountPanel3Layout);
        accountPanel3Layout.setHorizontalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(lbAccount3)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        accountPanel3Layout.setVerticalGroup(
            accountPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lbAccount3)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lbTitle.setText("Dashboard");

        lbInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo1.setText("Welcome to InfoPharma Ordering System");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbInfo1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(stockPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(accountPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pendingPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(92, 92, 92))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInfo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stockPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pendingPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(accountPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(salesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(59, 59, 59))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel accountPanel3;
    private javax.swing.JLabel lbAccount3;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbPending4;
    private javax.swing.JLabel lbSales2;
    private javax.swing.JLabel lbStock1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JPanel pendingPanel4;
    private javax.swing.JPanel salesPanel2;
    private javax.swing.JPanel stockPanel1;
    // End of variables declaration//GEN-END:variables
}
