/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;





/**
 *
 * @author mehzanazkhan
 */


import sa_orders.SA_ORD_API;
import database.DBConnection;
import main.java.PU_COMMS_API_Impl;
import main.java.SA_COMMS_API_Impl;


public class NewOrder extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewOrder.class.getName());
    private Orders ordersPanel;
    private final SA_COMMS_API_Impl saApi;
    private final PU_COMMS_API_Impl puCommsApi;


    

    /**
     * Creates new form NewOrder
     */
    public NewOrder(java.awt.Frame parent, boolean modal, Orders ordersPanel) {
        super(parent, modal);
        this.ordersPanel = ordersPanel;
        initComponents();
        
        
        saApi = new SA_COMMS_API_Impl();
        puCommsApi = new PU_COMMS_API_Impl();
        System.out.println("NewOrder dialog initialized.");

        
        
        javax.swing.table.DefaultTableModel model = new javax.swing.table.DefaultTableModel(
        new String[]{"Product ID", "Quantity"}, 0
        );

        jTableOrder.setModel(model);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableOrder = new javax.swing.JTable();
        btnAddItem = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        btnSubmitOrder = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Product ID", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableOrder);

        btnAddItem.setBackground(new java.awt.Color(0, 0, 51));
        btnAddItem.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnAddItem.setForeground(new java.awt.Color(255, 255, 255));
        btnAddItem.setText("+ Add Item");
        btnAddItem.addActionListener(this::btnAddItemActionPerformed);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        jLabel1.setText("Create a new order");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Enter a valid product ID and click add item, then select the quantity");

        txtProductID.setText("Enter Product ID...");
        txtProductID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtProductID.addActionListener(this::txtProductIDActionPerformed);

        btnSubmitOrder.setBackground(new java.awt.Color(0, 0, 153));
        btnSubmitOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnSubmitOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitOrder.setText("Submit Order");
        btnSubmitOrder.addActionListener(this::btnSubmitOrderActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("- Remove Item");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 40, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSubmitOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddItem))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSubmitOrder)
                    .addComponent(jButton2))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        String productId = txtProductID.getText().trim();

        if (productId.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a Product ID.");
            return;
            
        }
        
        boolean validProduct = true;
        //temporarily have this until connected with backend to look up if the product with id exists
        //as well as if the product is in stock in SA - will check from the catalogue
        //code calling the method in backend added here instead
        
        
        if (!validProduct) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid Product ID.");
            return;
        }
        
        String q = javax.swing.JOptionPane.showInputDialog(this, "Enter quantity:");

        if (q == null) return;

        int quantity;

        try {
            quantity = Integer.parseInt(q);
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Invalid quantity.");
            return;
        }

        if (quantity <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be above 0!");
            return;
        }
        
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTableOrder.getModel();

        model.addRow(new Object[]{productId, quantity});
        
        txtProductID.setText("");
        
        
        
        
        
        
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

    private void btnSubmitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOrderActionPerformed
                                           
    javax.swing.table.DefaultTableModel model =
        (javax.swing.table.DefaultTableModel) jTableOrder.getModel();

    int rowCount = model.getRowCount();
    if (rowCount == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Add at least one item.");
        return;
    }

    int[] itemIDs = new int[rowCount];
    int[] quantities = new int[rowCount];

    for (int i = 0; i < rowCount; i++) {
        try {
            itemIDs[i] = parseProductId(model.getValueAt(i, 0).toString());
            quantities[i] = Integer.parseInt(model.getValueAt(i, 1).toString());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Invalid product ID or quantity on row " + (i + 1) + ".",
                "Invalid Input",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        if (quantities[i] <= 0) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Quantity must be above 0 on row " + (i + 1) + ".",
                "Invalid Quantity",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
            return;
        }
    }

    java.math.BigDecimal[] qtyArray = new java.math.BigDecimal[rowCount];
    for (int i = 0; i < rowCount; i++) {
        qtyArray[i] = new java.math.BigDecimal(quantities[i]);
    }

    String username = "cosymed";

    System.out.println("Submitting order to SA...");
    System.out.println("Username: " + username);

    String orderResponse = saApi.newOrder(username);
    System.out.println("SA newOrder returned: " + orderResponse);

    if (orderResponse == null || orderResponse.isBlank()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to create order in SA.");
        return;
    }

    String orderId;
    try {
        com.fasterxml.jackson.databind.ObjectMapper mapper =
            new com.fasterxml.jackson.databind.ObjectMapper();
        com.fasterxml.jackson.databind.JsonNode root = mapper.readTree(orderResponse);

        System.out.println("=== SA NEW ORDER RESPONSE DEBUG ===");
        System.out.println("Raw SA response: " + orderResponse);
        System.out.println("All JSON fields: " + (root.fieldNames().hasNext() ? root.fieldNames() : "NO_FIELDS"));
        
        if (root.get("orderId") == null) {
            System.out.println("ERROR: 'orderId' field not found in SA response!");
            System.out.println("Available fields: " + root.fieldNames());
            javax.swing.JOptionPane.showMessageDialog(this, "SA response did not contain a valid orderId.");
            return;
        }
        
        orderId = root.get("orderId").asText();
        System.out.println("Extracted orderId: [" + orderId + "]");
        System.out.println("Order ID length: " + orderId.length());
        System.out.println("Order ID matches numeric format (like 22026-04-12): " + 
            orderId.matches("\\d{5}-\\d{2}-\\d{2}"));
        
        if (orderId.isBlank()) {
            javax.swing.JOptionPane.showMessageDialog(this, "SA response did not contain a valid orderId.");
            return;
        }

        orderId = root.get("orderId").asText();
    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to parse order ID from SA response.");
        return;
    }



    System.out.println("Parsed SA orderId: " + orderId);

    boolean added = saApi.addItems(orderId, itemIDs, qtyArray);
    System.out.println("SA addItems returned: " + added);

    if (!added) {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to add items to SA order.");
        return;
    }

    boolean submitted = saApi.submitOrder(orderId);
    System.out.println("SA submitOrder returned: " + submitted);

    if (!submitted) {
        javax.swing.JOptionPane.showMessageDialog(this, "Failed to submit order to SA.");
        return;
    }
    
        //submitted SA order in the local CA database so Orders.loadOrders() can pick it up.
    try {
        SA_ORD_API localOrderApi = new SA_ORD_API(DBConnection.getConnection());
        boolean inserted = localOrderApi.insertOrder(orderId, false);
        if (inserted) {
            localOrderApi.addItems(orderId, itemIDs, quantities);
        } else {
            System.err.println("Failed to persist SA order locally: " + orderId);
        }
    } catch (Exception e) {
        e.printStackTrace();
    }

    int totalQuantity = 0;
    for (int q : quantities) {
        totalQuantity += q;
    }

    String today = new java.text.SimpleDateFormat("dd/MM/yyyy").format(new java.util.Date());

    if (ordersPanel != null) {
        ordersPanel.addOrderRow(new Object[]{
            orderId,
            today,
            "Submitted to SA",
            itemIDs[0],
            totalQuantity,
            0.0
        });
        ordersPanel.refreshOrders();
        ordersPanel.refreshBalance();
    }

    javax.swing.JOptionPane.showMessageDialog(
        this,
        "Order submitted successfully!\nSA Order ID: " + orderId
    );

    this.dispose();

    }//GEN-LAST:event_btnSubmitOrderActionPerformed

    private int parseProductId(String value) {
        String digitsOnly = value.replaceAll("\\D+", "");
        if (digitsOnly.isEmpty()) {
            throw new NumberFormatException("No numeric product id");
        }
        return Integer.parseInt(digitsOnly);
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int selectedRow = jTableOrder.getSelectedRow();

        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a item to remove.");
            return;
        }

        int confirm = javax.swing.JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete this item?",
            "Confirm Delete",
            javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (confirm == javax.swing.JOptionPane.YES_OPTION) {
            javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTableOrder.getModel();

            model.removeRow(selectedRow);

            javax.swing.JOptionPane.showMessageDialog(this,
                "Item removed successfully.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnSubmitOrder;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableOrder;
    private javax.swing.JTextField txtProductID;
    // End of variables declaration//GEN-END:variables
}
