/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;


/**
 *
 * @author mehzanazkhan
 */

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import customer.CustomerAPI_Impl;
import java.util.LinkedHashMap;
import java.util.Map;
import login.SA_LOGIN_API;
import main.java.SA_COMMS_API_Impl;
import sa_orders.SA_ORD_API;


public class Orders extends javax.swing.JPanel {

    private static int orderCounter = 1;
    private SA_ORD_API saOrdApi;
    private SA_COMMS_API_Impl saCommsApi;
    private SA_LOGIN_API loginApi;
    private CustomerAPI_Impl customerApi;

public Orders() {
    initComponents();

    saOrdApi = new SA_ORD_API(database.DBConnection.getConnection());
    saCommsApi = new SA_COMMS_API_Impl();
    loginApi = new SA_LOGIN_API();
    customerApi = new CustomerAPI_Impl();

    loadOrders();
    refreshStatusesFromSA();
    loadCatalogue();
    loadLoggedInBalance();

    jCatalogueSearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            searchCatalogue(jCatalogueSearchBar.getText());
        }
    });
}


    
    /**
     * Creates new form Orders
     */

        
        //THIS USES THE WRONG API
        /*
        orderApi = new CA_OnlineOrderAPI_Impl(
        new sa_orders.SA_ORD_API(DBConnection.getConnection()),
        new merchant.SA_Merchant_API_Impl(DBConnection.getConnection()), 
        new stock.CA_Stock_API_Impl(DBConnection.getConnection()),
        DBConnection.getConnection()
        );
        */
        


    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbInfo1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jOrdersTable = new javax.swing.JTable();
        lbInfo2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jCatalogueTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jCatalogueSearchBar = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        AccStatus = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lbInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo1.setText("Welcome to the InfoPharma Ordering System");

        jTabbedPane2.setBackground(new java.awt.Color(239, 239, 239));

        jOrdersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Date", "Status", "Items", "Quantity", "Total cost"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jOrdersTable);
        if (jOrdersTable.getColumnModel().getColumnCount() > 0) {
            jOrdersTable.getColumnModel().getColumn(2).setHeaderValue("Status");
            jOrdersTable.getColumnModel().getColumn(3).setHeaderValue("Items");
            jOrdersTable.getColumnModel().getColumn(4).setHeaderValue("Quantity");
            jOrdersTable.getColumnModel().getColumn(5).setResizable(false);
            jOrdersTable.getColumnModel().getColumn(5).setHeaderValue("Total cost");
        }

        lbInfo2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo2.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo2.setText("All your orders are displayed here:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbInfo2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 941, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("My Orders", jPanel3);

        jPanel4.setBackground(new java.awt.Color(239, 239, 239));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jCatalogueTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jCatalogueTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 901, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Search:");

        jCatalogueSearchBar.setText("Search by product name.....");
        jCatalogueSearchBar.addActionListener(this::jCatalogueSearchBarActionPerformed);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCatalogueSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jCatalogueSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Product Catalogue", jPanel4);

        jPanel5.setBackground(new java.awt.Color(239, 239, 239));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setText("Outstanding Balance:");

        jLabel3.setBackground(new java.awt.Color(239, 239, 239));
        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Account Balance", jPanel5);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Orders to InfoPharma");

        AccStatus.setFont(new java.awt.Font("Helvetica Neue", 1, 15)); // NOI18N
        AccStatus.setText("Normal");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel5.setText("Account Status:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(AccStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AccStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View order invoice");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        btnPlaceOrder.setBackground(new java.awt.Color(0, 0, 51));
        btnPlaceOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setText("+ Place Order");
        btnPlaceOrder.addActionListener(this::btnPlaceOrderActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbInfo1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnPlaceOrder)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInfo1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents


    private void loadOrders() {
        try {
            javax.swing.table.DefaultTableModel model =
                (javax.swing.table.DefaultTableModel) jOrdersTable.getModel();

            model.setRowCount(0);

            java.sql.ResultSet rs = saOrdApi.getAllOrders();

            if (rs == null) return;

            while (rs.next()) {
                String orderId = rs.getString("order_ref");
                String status = rs.getString("status");
                int productId = rs.getInt("product_id");
                int quantity = rs.getInt("quantity");
                java.sql.Timestamp orderTimestamp = rs.getTimestamp("order_date");

                String date = orderTimestamp == null
                    ? "-"
                    : new java.text.SimpleDateFormat("dd/MM/yyyy").format(orderTimestamp);

                double totalCost = rs.getDouble("total_cost");

                model.addRow(new Object[]{
                    orderId,
                    date,
                    status,
                    productId,
                    quantity,
                    totalCost
                });
            }

        } catch (Exception e) {
                e.printStackTrace();
        }
    }

public void refreshOrders() {
    loadOrders();
    refreshStatusesFromSA();
}

    public void refreshBalance() {
        loadLoggedInBalance();
    }
    
    
    
private void loadCatalogue() {
    try {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jCatalogueTable.getModel();
        model.setRowCount(0);

String jsonResponse = saCommsApi.getActiveCatalogue("username=cosymed");
System.out.println("RAW catalogue response: " + jsonResponse);

if (jsonResponse == null || jsonResponse.isBlank()) {
    javax.swing.JOptionPane.showMessageDialog(this,
        "No catalogue data returned from SA.");
    return;
}

Map<Integer, String> catalogueItems = parseCatalogueResponse(jsonResponse);
System.out.println("Parsed catalogue size: " + catalogueItems.size());

        for (Map.Entry<Integer, String> item : catalogueItems.entrySet()) {
            model.addRow(new Object[]{item.getKey(), item.getValue()});
        }

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Failed to load SA catalogue: " + e.getMessage());
    }
}
    
    
private void searchCatalogue(String searchText) {
    try {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jCatalogueTable.getModel();
        model.setRowCount(0);

        String jsonResponse = saCommsApi.getActiveCatalogue("username=cosymed");

        if (jsonResponse == null || jsonResponse.isBlank()) {
            return;
        }

        Map<Integer, String> catalogueItems = parseCatalogueResponse(jsonResponse);

        String search = searchText == null ? "" : searchText.trim().toLowerCase();

        for (Map.Entry<Integer, String> item : catalogueItems.entrySet()) {
            String productName = item.getValue() == null ? "" : item.getValue().toLowerCase();

            if (search.isBlank() || productName.contains(search)) {
                model.addRow(new Object[]{item.getKey(), item.getValue()});
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

    //code for balance
private void loadLoggedInBalance() {
    try {
        String response = saCommsApi.getBalance("username=cosymed");
        System.out.println("SA balance response: " + response);

        if (response == null || response.isBlank()) {
            jLabel3.setText("£0.00");
            return;
        }

        double balance = Double.parseDouble(response.trim());
        jLabel3.setText(String.format("£%.2f", balance));

    } catch (Exception e) {
        jLabel3.setText("£0.00");
        e.printStackTrace();
    }
}
    
    
    
    public static String generateOrderID(){
        return String.format("ORD%05d", orderCounter++);
    }
    
    
    
    public void addOrderRow(Object[] row){
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jOrdersTable.getModel();
        model.addRow(row);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         


    }                                        

    private void jCatalogueSearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCatalogueSearchBarActionPerformed
        String text = jCatalogueSearchBar.getText();
        searchCatalogue(text);
    }//GEN-LAST:event_jCatalogueSearchBarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

    int selectedRow = jOrdersTable.getSelectedRow();

    if (selectedRow == -1) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Please select an order to view the invoice of.");
        return;
    }

    String orderId = jOrdersTable.getValueAt(selectedRow, 0).toString();

    try {
        System.out.println("=== INVOICE REQUEST DEBUG ===");
        System.out.println("Selected row: " + selectedRow);
        System.out.println("Order ID from table (column 0): [" + orderId + "]");
        System.out.println("Order ID length: " + orderId.length());
        System.out.println("Order ID type/format: appears to be " + 
            (orderId.matches("\\d{5}-\\d{2}-\\d{2}") ? "NUMERIC (like 22026-04-12)" : "OTHER"));
        
        String response = saCommsApi.getInvoice("orderId=" + orderId);
        System.out.println("SA invoice response for " + orderId + ": " + response);

        if (response == null || response.isBlank()) {
            showInvoiceFallback(orderId, "No invoice data returned from SA.");
            return;
        }

        // If the response appears to be an SA error message instead of invoice text,
        // fallback to a locally generated invoice view.
        if (response.toLowerCase().contains("couldnt")
            || response.toLowerCase().contains("couldn't")
            || response.toLowerCase().contains("could not")
            || response.toLowerCase().contains("invoice details")) {
            showInvoiceFallback(orderId, response);
            return;
        }
        javax.swing.JTextArea area = new javax.swing.JTextArea(response);
        area.setEditable(false);
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));

        javax.swing.JScrollPane pane = new javax.swing.JScrollPane(area);
        pane.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.JOptionPane.showMessageDialog(
            this,
            pane,
            "Order Invoice",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception e) {
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this,
            "Failed to load invoice from SA.");
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
    System.out.println("btnPlaceOrder clicked, AccStatus = '" + AccStatus.getText() + "'");
    if (AccStatus.getText().equals("Normal")){
        java.awt.Window parentWindow = javax.swing.SwingUtilities.getWindowAncestor(this);

        NewOrder dialog;
        if (parentWindow instanceof java.awt.Frame) {
            dialog = new NewOrder((java.awt.Frame) parentWindow, true, this);
        } else {
            dialog = new NewOrder(null, true, this);
        }

        dialog.setLocationRelativeTo(parentWindow);
        dialog.setVisible(true);

        // Reload from DB after modal closes so newly submitted orders are shown.
        refreshOrders();
    } else {
        javax.swing.JOptionPane.showMessageDialog(this,
                "Account status must be normal to place an order.");
    
    }
        
    

    }//GEN-LAST:event_btnPlaceOrderActionPerformed

private Map<Integer, String> parseCatalogueResponse(String jsonResponse) {
    Map<Integer, String> result = new LinkedHashMap<>();

    try {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(jsonResponse);

        JsonNode itemIds = root.get("item_id");
        JsonNode descriptions = root.get("description");

        if (itemIds != null && descriptions != null && itemIds.isArray() && descriptions.isArray()) {
            int count = Math.min(itemIds.size(), descriptions.size());

            for (int i = 0; i < count; i++) {
                int productId = itemIds.get(i).asInt();
                String productName = descriptions.get(i).asText();

                result.put(productId, productName);
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }

    return result;
}

private void showInvoiceFallback(String orderId, String failureReason) {
    Map<String, Integer> orderItems = saOrdApi.viewOrder(orderId);
    StringBuilder invoice = new StringBuilder();

    invoice.append("SA invoice not available for order: ").append(orderId).append("\n");
    invoice.append("Failure reason: ").append(failureReason).append("\n\n");
    invoice.append("Local order details below:\n");
    invoice.append("---------------------------\n");

    if (orderItems.isEmpty()) {
        invoice.append("No local order items found for this order.\n");
    } else {
        invoice.append(String.format("%-40s %10s\n", "Product", "Quantity"));
        invoice.append("------------------------------------------------\n");
        for (Map.Entry<String, Integer> item : orderItems.entrySet()) {
            invoice.append(String.format("%-40s %10d\n", item.getKey(), item.getValue()));
        }
    }

    invoice.append("\n");
    invoice.append("Note: This is a local order summary because SA invoice details could not be retrieved.\n");
    invoice.append("If some products are missing or quantities differ, please verify the order in SA and retry.\n");

    javax.swing.JTextArea area = new javax.swing.JTextArea(invoice.toString());
    area.setEditable(false);
    area.setLineWrap(true);
    area.setWrapStyleWord(true);
    area.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 13));

    javax.swing.JScrollPane pane = new javax.swing.JScrollPane(area);
    pane.setPreferredSize(new java.awt.Dimension(500, 320));

    javax.swing.JOptionPane.showMessageDialog(
        this,
        pane,
        "Order Summary - Invoice Unavailable",
        javax.swing.JOptionPane.INFORMATION_MESSAGE
    );
}

private int extractInt(JsonNode node, String... keys) {
    for (String key : keys) {
        if (node.has(key) && !node.get(key).isNull()) {
            try {
                return node.get(key).asInt();
            } catch (Exception ignored) {
            }
        }
    }
    return 0;
}

private String extractString(JsonNode node, String... keys) {
    for (String key : keys) {
        if (node.has(key) && !node.get(key).isNull()) {
            try {
                return node.get(key).asText();
            } catch (Exception ignored) {
            }
        }
    }
    return "";
}

private void refreshStatusesFromSA() {
    try {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jOrdersTable.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            

            
            String orderId = String.valueOf(model.getValueAt(i, 0));

        if (orderId == null || orderId.isBlank()) { 
            continue;
        }

        if (!orderId.startsWith("220")) {
            continue;
        }

        String response = saCommsApi.getOrderStatuses("orderId=" + orderId);
            
            System.out.println("SA status response for " + orderId + ": " + response);

            if (response == null || response.isBlank() || response.equals("ORDER_NOT_FOUND")) {
                continue;
            }

            String status = parseOrderStatusResponse(response);
            if (!status.isBlank()) {
                model.setValueAt(status, i, 2);

                if (status.equalsIgnoreCase("delivered")) {
                    recordDeliveredOrderLocally(orderId);
                }
            }
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
}

private String parseOrderStatusResponse(String jsonResponse) {
    try {
        ObjectMapper mapper = new ObjectMapper();
        JsonNode root = mapper.readTree(jsonResponse);

        if (root.has("orderStatus") && !root.get("orderStatus").isNull()) {
            return root.get("orderStatus").asText();
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
    return "";
}

private void recordDeliveredOrderLocally(String orderId) {
    try {

        // Record delivery in local database
        boolean success = saOrdApi.recordDelivery(orderId);
        if (success) {
            System.out.println("Delivery recorded locally for order: " + orderId);
        } else {
            System.out.println("Failed to record delivery for order: " + orderId);
        }

        String localStatus = saOrdApi.getLocalOrderStatus(orderId);

        if ("delivered".equalsIgnoreCase(localStatus)) {
            return;
        }

        stock.CA_Stock_API_Impl stockApi =
            new stock.CA_Stock_API_Impl(database.DBConnection.getConnection());

        Map<Integer, Integer> items = saOrdApi.getOrderItems(orderId);

for (Map.Entry<Integer, Integer> entry : items.entrySet()) {
    int productId = entry.getKey();
    int quantity = entry.getValue();

    System.out.println("Delivered order: " + orderId);
    System.out.println("Updating stock for product " + productId + " by " + quantity);

    stockApi.recordDelivery(productId, quantity, null);
}

        saOrdApi.updateOrderStatus(orderId, "delivered");
        System.out.println("Delivery recorded locally for order: " + orderId);

    } catch (Exception e) {
    }
}



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AccStatus;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton jButton2;
    private javax.swing.JTextField jCatalogueSearchBar;
    private javax.swing.JTable jCatalogueTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jOrdersTable;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbInfo2;
    // End of variables declaration//GEN-END:variables
}
