/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

import database.DBConnection;
import java.util.ArrayList;
import java.util.List;
import merchant.SA_Merchant_API;
import merchant.SA_Merchant_API_Impl;
import sa_orders.SA_ORD_API;

/**
 *
 * @author LukeBravermanCityUniversity
 */
public class Sales extends javax.swing.JPanel {
    private static final double VAT_RATE = 0.20;
    private static final double ACCOUNT_HOLDER_DISCOUNT_RATE = 0.10;
    private static final String[][] PRODUCT_CATALOG = {
        {"P001", "Paracetamol 500mg", "2.50"},
        {"P002", "Ibuprofen 200mg", "4.20"},
        {"P003", "Cough Syrup", "6.80"},
        {"P004", "Vitamin C Tablets", "8.10"}
    };
    private boolean cardDetailsCaptured;
    private String cardSummary = "";
    private String cardNumberForBackend = "";
    private String cardExpiryForBackend = "";
    private final SA_Merchant_API merchantAPI = new SA_Merchant_API_Impl(DBConnection.getConnection());
    private final SA_ORD_API saOrdApi = new SA_ORD_API(DBConnection.getConnection());

    /**
     * Creates new form Sales
     */
    public Sales() {
        initComponents();
        makeContentScrollable();
        initialiseSalesPage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        jPanel3.setBackground(new java.awt.Color(252, 252, 252));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(220, 220, 220)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setText("Sale Items");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Add products to the current sale   ");

        jLabel15.setText("Product");

        jLabel16.setText("Quantity");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);

        jTextField3.setText("1");
        jTextField3.addActionListener(this::jTextField3ActionPerformed);

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("No items added yet. Select products above to add to sale. ");

        jButton3.setBackground(new java.awt.Color(20, 20, 20));
        jButton3.setForeground(new java.awt.Color(252, 252, 252));
        jButton3.setLabel("+ Add");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(103, 103, 103)
                                .addComponent(jButton3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel17)))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addGap(54, 54, 54)
                .addComponent(jLabel17)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(245, 245, 245));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jLabel1.setText("Point Of Sale");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Process customer sales and generate invoices");

        jPanel1.setBackground(new java.awt.Color(252, 252, 252));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setText("Sale Items");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Add products to the current sale   ");

        jLabel5.setText("Product");

        jLabel6.setText("Quantity");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jTextField1.setText("1");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("No items added yet. Added products will appear in the table below.");

        jButton1.setBackground(new java.awt.Color(20, 20, 20));
        jButton1.setForeground(new java.awt.Color(252, 252, 252));
        jButton1.setLabel("+ Add");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Quantity", "Unit Price", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addComponent(jButton1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 733, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel8.setText("Customer Details");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("Customer Type");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(this::jComboBox2ActionPerformed);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel10.setText("Payment method");

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox5.addActionListener(this::jComboBox5ActionPerformed);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setText("Account ID");

        jTextField2.addActionListener(this::jTextField2ActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(654, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel18.setText("Sale Summary");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel19.setText("£0.00");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setText("Discount:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel23.setText("Total: ");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel24.setText("VAT (20%):");

        jButton2.setBackground(new java.awt.Color(20, 20, 20));
        jButton2.setForeground(new java.awt.Color(252, 252, 252));
        jButton2.setLabel("Complete Sale");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setText("Subtotal:");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel21.setText("£0.00");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel22.setText("£0.00");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel25.setText("£0.00");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel25))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel22)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jButton2.getAccessibleContext().setAccessibleName("jButton");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(50, 50, 50)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        addSelectedItemToSale();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        updateAccountIdVisibility();
        updateSummary();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        handlePaymentMethodSelection();
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        completeSale();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void makeContentScrollable() {
        removeAll();
        setLayout(new java.awt.BorderLayout());

        javax.swing.JPanel contentPanel = new javax.swing.JPanel();
        contentPanel.setBackground(getBackground());
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(23, 29, 21, 29));
        contentPanel.setLayout(new javax.swing.BoxLayout(contentPanel, javax.swing.BoxLayout.Y_AXIS));

        jLabel1.setAlignmentX(LEFT_ALIGNMENT);
        jLabel2.setAlignmentX(LEFT_ALIGNMENT);
        jPanel1.setAlignmentX(LEFT_ALIGNMENT);
        jPanel2.setAlignmentX(LEFT_ALIGNMENT);
        jPanel4.setAlignmentX(LEFT_ALIGNMENT);

        contentPanel.add(jLabel1);
        contentPanel.add(javax.swing.Box.createVerticalStrut(6));
        contentPanel.add(jLabel2);
        contentPanel.add(javax.swing.Box.createVerticalStrut(50));
        contentPanel.add(jPanel1);
        contentPanel.add(javax.swing.Box.createVerticalStrut(29));
        contentPanel.add(jPanel2);
        contentPanel.add(javax.swing.Box.createVerticalStrut(18));
        contentPanel.add(jPanel4);

        javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(contentPanel);
        scrollPane.setBorder(null);
        scrollPane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);

        add(scrollPane, java.awt.BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    private void initialiseSalesPage() {
        jComboBox1.removeAllItems();
        for (String[] product : PRODUCT_CATALOG) {
            jComboBox1.addItem(product[0] + " - " + product[1]);
        }

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Occasional Customer", "Account Holder"
        }));

        jTextField2.setText("");
        cardDetailsCaptured = false;
        cardSummary = "";
        jTable1.setRowHeight(24);
        jTable1.getTableHeader().setReorderingAllowed(false);
        updateAccountIdVisibility();
        updatePaymentMethodOptions();
        updateSummary();
    }

    private void addSelectedItemToSale() {
        int selectedIndex = jComboBox1.getSelectedIndex();
        if (selectedIndex < 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Select a product to add.");
            return;
        }

        int quantity;
        try {
            quantity = Integer.parseInt(jTextField1.getText().trim());
        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter a valid quantity.");
            return;
        }

        if (quantity <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
            return;
        }

        String[] product = PRODUCT_CATALOG[selectedIndex];
        double unitPrice = Double.parseDouble(product[2]);
        double lineTotal = unitPrice * quantity;
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();

        int existingRow = findRowByProductId(model, product[0]);
        if (existingRow >= 0) {
            int updatedQuantity = ((Number) model.getValueAt(existingRow, 2)).intValue() + quantity;
            model.setValueAt(updatedQuantity, existingRow, 2);
            model.setValueAt(formatCurrency(unitPrice * updatedQuantity), existingRow, 4);
        } else {
            model.addRow(new Object[] {
                product[0],
                product[1],
                quantity,
                formatCurrency(unitPrice),
                formatCurrency(lineTotal)
            });
        }

        jTextField1.setText("1");
        jLabel7.setText(model.getRowCount() + " item(s) recorded in this sale.");
        updateSummary();
    }

    private int findRowByProductId(javax.swing.table.DefaultTableModel model, String productId) {
        for (int row = 0; row < model.getRowCount(); row++) {
            if (productId.equals(String.valueOf(model.getValueAt(row, 0)))) {
                return row;
            }
        }
        return -1;
    }

    private void updateSummary() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        double subtotal = 0.0;

        for (int row = 0; row < model.getRowCount(); row++) {
            subtotal += parseCurrency(String.valueOf(model.getValueAt(row, 4)));
        }

        double discount = calculateDiscount(subtotal);
        double discountedSubtotal = subtotal - discount;
        double vat = discountedSubtotal * VAT_RATE;
        double total = discountedSubtotal + vat;

        jLabel19.setText(formatCurrency(subtotal));
        jLabel25.setText(formatCurrency(discount));
        jLabel21.setText(formatCurrency(vat));
        jLabel22.setText(formatCurrency(total));

        if (model.getRowCount() == 0) {
            jLabel7.setText("No items added yet. Added products will appear in the table below.");
        }
    }

    private double calculateDiscount(double subtotal) {
        if ("Account Holder".equals(String.valueOf(jComboBox2.getSelectedItem()))) {
            return subtotal * ACCOUNT_HOLDER_DISCOUNT_RATE;
        }
        return 0.0;
    }

    private void completeSale() {
        javax.swing.table.DefaultTableModel model =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        if (model.getRowCount() == 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "Add at least one item before completing the sale.");
            return;
        }

        if ("Account Holder".equals(String.valueOf(jComboBox2.getSelectedItem()))
                && jTextField2.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Enter an account ID for account holder sales.");
            return;
        }

        if ("Credit".equals(String.valueOf(jComboBox5.getSelectedItem()))
                && !"Account Holder".equals(String.valueOf(jComboBox2.getSelectedItem()))) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Credit payment is only available for account holder sales."
            );
            return;
        }

        if ("Credit".equals(String.valueOf(jComboBox5.getSelectedItem()))
                && jTextField2.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Enter an account ID before using Credit payment."
            );
            return;
        }

        if ("Card".equals(String.valueOf(jComboBox5.getSelectedItem())) && !cardDetailsCaptured) {
            if (!captureCardDetails()) {
                return;
            }
        }

        double totalAmount = parseCurrency(jLabel22.getText());
        // Block sale completion unless payment step succeeds.
        boolean paymentOk = callPaymentBackend(totalAmount);
        if (!paymentOk) {
            javax.swing.JOptionPane.showMessageDialog(this, "Payment failed. Sale was not completed.");
            return;
        }

        // Temporary hook to pass sale item payload to backend until final DB write design is confirmed.
        boolean recorded = merchantAPI.recordCustomerPurchase(
            getSelectedCustomerId(),
            buildSaleItemsForBackend(model),
            totalAmount,
            String.valueOf(jComboBox5.getSelectedItem())
        );

        if (!recorded) {
            javax.swing.JOptionPane.showMessageDialog(this, "Sale could not be recorded.");
            return;
        }

        mirrorSaleInOrdersTable(model);

        showRetailInvoice();

        model.setRowCount(0);
        jTextField1.setText("1");
        jTextField2.setText("");
        jComboBox2.setSelectedIndex(0);
        jComboBox5.setSelectedIndex(0);
        cardDetailsCaptured = false;
        cardSummary = "";
        cardNumberForBackend = "";
        cardExpiryForBackend = "";
        updateSummary();
    }

    private void mirrorSaleInOrdersTable(javax.swing.table.DefaultTableModel model) {
        int rowCount = model.getRowCount();
        if (rowCount == 0) {
            return;
        }

        int[] itemIDs = new int[rowCount];
        int[] quantities = new int[rowCount];

        for (int i = 0; i < rowCount; i++) {
            itemIDs[i] = parseIdNumber(String.valueOf(model.getValueAt(i, 0)));
            quantities[i] = Integer.parseInt(String.valueOf(model.getValueAt(i, 2)));
        }

        String orderId = saOrdApi.newOrder();
        saOrdApi.addItems(orderId, itemIDs, quantities);
        saOrdApi.submitOrder(orderId);
    }

    private boolean callPaymentBackend(double totalAmount) {
        String paymentMethod = String.valueOf(jComboBox5.getSelectedItem());
        String posOrderId = generateFrontendOrderId();

        if ("Card".equalsIgnoreCase(paymentMethod)) {
            return merchantAPI.processCardPayment(posOrderId, cardNumberForBackend, cardExpiryForBackend, totalAmount);
        }

        if ("Cash".equalsIgnoreCase(paymentMethod)) {
            return merchantAPI.processCashPayment(posOrderId, totalAmount);
        }

        if ("Account".equalsIgnoreCase(paymentMethod) || "Credit".equalsIgnoreCase(paymentMethod)) {
            return merchantAPI.processCreditPayment(getSelectedCustomerId(), totalAmount);
        }

        System.out.println("No matching backend payment method for: " + paymentMethod);
        return false;
    }

    private String generateFrontendOrderId() {
        return "ONL-" + java.time.LocalDateTime.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("yyyyMMddHHmmss"))
            + "-" + java.util.UUID.randomUUID().toString().substring(0, 8).toUpperCase();
    }

    private List<Object[]> buildSaleItemsForBackend(javax.swing.table.DefaultTableModel model) {
        List<Object[]> saleItems = new ArrayList<>();

        for (int row = 0; row < model.getRowCount(); row++) {
            int productId = parseIdNumber(String.valueOf(model.getValueAt(row, 0)));
            int quantity = Integer.parseInt(String.valueOf(model.getValueAt(row, 2)));
            double unitPrice = parseCurrency(String.valueOf(model.getValueAt(row, 3)));

            saleItems.add(new Object[] {productId, quantity, unitPrice});
        }

        return saleItems;
    }

    private int getSelectedCustomerId() {
        if (!"Account Holder".equals(String.valueOf(jComboBox2.getSelectedItem()))) {
            return 0;
        }

        return parseIdNumber(jTextField2.getText().trim());
    }

    private int parseIdNumber(String value) {
        String digitsOnly = value.replaceAll("\\D+", "");
        if (digitsOnly.isEmpty()) {
            return 0;
        }
        return Integer.parseInt(digitsOnly);
    }

    private void showRetailInvoice() {
        javax.swing.table.DefaultTableModel sourceModel =
            (javax.swing.table.DefaultTableModel) jTable1.getModel();
        javax.swing.table.DefaultTableModel invoiceModel = new javax.swing.table.DefaultTableModel(
            new Object[][] {},
            new String[] {"Item", "Packages", "Package Cost, £", "Amount, £"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (int row = 0; row < sourceModel.getRowCount(); row++) {
            invoiceModel.addRow(new Object[] {
                sourceModel.getValueAt(row, 1),
                sourceModel.getValueAt(row, 2),
                stripCurrency(String.valueOf(sourceModel.getValueAt(row, 3))),
                stripCurrency(String.valueOf(sourceModel.getValueAt(row, 4)))
            });
        }

        javax.swing.JTable invoiceTable = new javax.swing.JTable(invoiceModel);
        invoiceTable.setRowHeight(22);
        invoiceTable.getTableHeader().setReorderingAllowed(false);
        invoiceTable.setEnabled(false);
        invoiceTable.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 13));
        invoiceTable.getTableHeader().setFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 13));
        invoiceTable.setShowGrid(true);
        invoiceTable.setGridColor(java.awt.Color.DARK_GRAY);

        javax.swing.JScrollPane tableScrollPane = new javax.swing.JScrollPane(invoiceTable);
        tableScrollPane.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.DARK_GRAY));
        tableScrollPane.setPreferredSize(new java.awt.Dimension(460, 165));

        javax.swing.JLabel titleLabel = new javax.swing.JLabel("9.7 Appendix 7: Retail Invoice");
        titleLabel.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 18));

        javax.swing.JLabel briefLabel = new javax.swing.JLabel("InfoPharma ORDERING SYSTEM: STUDENT'S BRIEF");
        briefLabel.setFont(new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 11));

        javax.swing.JTextArea leftAddress = createInvoiceTextArea(buildCustomerAddressBlock());
        javax.swing.JTextArea rightAddress = createInvoiceTextArea(
            "Cosymed Ltd.,\n"
            + "3, High Level Drive,\n"
            + "Sydenham,\n"
            + "SE26 3ET\n"
            + "Phone: 0208 778 0124\n"
            + "Fax: 0208 778 0125"
        );
        javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        headerPanel.setOpaque(false);
        headerPanel.add(titleLabel, java.awt.BorderLayout.WEST);
        headerPanel.add(briefLabel, java.awt.BorderLayout.EAST);

        javax.swing.JPanel addressPanel = new javax.swing.JPanel(new java.awt.GridLayout(1, 2, 80, 0));
        addressPanel.setOpaque(false);
        addressPanel.add(leftAddress);
        addressPanel.add(rightAddress);

        javax.swing.JPanel introPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        introPanel.setOpaque(false);

        javax.swing.JLabel dearLabel = new javax.swing.JLabel("Dear Customer,");
        dearLabel.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        introPanel.add(dearLabel, java.awt.BorderLayout.WEST);

        javax.swing.JPanel metaPanel = new javax.swing.JPanel(new java.awt.GridLayout(2, 1, 0, 8));
        metaPanel.setOpaque(false);

        javax.swing.JLabel invoiceLabel = new javax.swing.JLabel("INVOICE NO.: 197362", javax.swing.SwingConstants.CENTER);
        invoiceLabel.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 16));

        javax.swing.JLabel accountLabel = new javax.swing.JLabel(buildInvoiceAccountLine());
        accountLabel.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));

        metaPanel.add(invoiceLabel);
        metaPanel.add(accountLabel);

        javax.swing.JPanel metaWrapper = new javax.swing.JPanel();
        metaWrapper.setOpaque(false);
        metaWrapper.setLayout(new javax.swing.BoxLayout(metaWrapper, javax.swing.BoxLayout.Y_AXIS));
        metaWrapper.add(javax.swing.Box.createVerticalStrut(6));
        metaWrapper.add(metaPanel);

        introPanel.add(metaWrapper, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel tablePanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        tablePanel.setOpaque(false);
        tablePanel.add(tableScrollPane, java.awt.BorderLayout.CENTER);
        tablePanel.add(buildTotalsPanel(), java.awt.BorderLayout.SOUTH);

        javax.swing.JTextArea closingArea = createInvoiceTextArea(buildInvoiceFooterBlock());
        closingArea.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 0, 0));

        javax.swing.JPanel closingPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        closingPanel.setOpaque(false);
        closingPanel.add(closingArea, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel panel = new javax.swing.JPanel();
        panel.setLayout(new javax.swing.BoxLayout(panel, javax.swing.BoxLayout.Y_AXIS));
        panel.setBackground(java.awt.Color.WHITE);
        panel.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 18, 16, 18));
        panel.add(headerPanel);
        panel.add(javax.swing.Box.createVerticalStrut(24));
        panel.add(addressPanel);
        panel.add(javax.swing.Box.createVerticalStrut(18));
        panel.add(createInvoiceTextArea(buildInvoiceDateBlock()));
        panel.add(javax.swing.Box.createVerticalStrut(18));
        panel.add(introPanel);
        panel.add(javax.swing.Box.createVerticalStrut(14));
        panel.add(tablePanel);
        panel.add(javax.swing.Box.createVerticalStrut(18));
        panel.add(closingPanel);

        javax.swing.JOptionPane.showMessageDialog(
            this,
            panel,
            "Retail Invoice",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );
    }

    private javax.swing.JTextArea createInvoiceTextArea(String text) {
        javax.swing.JTextArea textArea = new javax.swing.JTextArea(text);
        textArea.setEditable(false);
        textArea.setOpaque(false);
        textArea.setLineWrap(true);
        textArea.setWrapStyleWord(true);
        textArea.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 14));
        textArea.setAlignmentX(LEFT_ALIGNMENT);
        return textArea;
    }

    private String buildCustomerAddressBlock() {
        String customerName = "Occasional Customer".equals(String.valueOf(jComboBox2.getSelectedItem()))
            ? "Walk-in Customer"
            : "Account Holder";
        String accountId = jTextField2.getText().trim().isEmpty() ? "CSM000123" : jTextField2.getText().trim();

        return customerName + "\n"
            + "27 Sainsbury Close,\n"
            + "Stratford,\n"
            + "Essex EJ6 5TJ\n\n"
            + "Account No: " + accountId;
    }

    private String buildInvoiceDateBlock() {
        String invoiceDate = java.time.LocalDate.now()
            .format(java.time.format.DateTimeFormatter.ofPattern("d MMMM yyyy"));
        return invoiceDate;
    }

    private String buildInvoiceAccountLine() {
        String accountId = jTextField2.getText().trim().isEmpty() ? "CSM000123" : jTextField2.getText().trim();
        return "Account No: " + accountId;
    }

    private String buildInvoiceFooterBlock() {
        String paymentMethod = String.valueOf(jComboBox5.getSelectedItem());
        String paymentDetails = cardSummary.isEmpty() ? paymentMethod : paymentMethod + " (" + cardSummary + ")";

        return "Payment Method: " + paymentDetails
            + "\n\nThank you for your valued custom. We look forward to receiving your payment in due course."
            + "\n\nYours sincerely,\n\nPharmaTech";
    }

    private javax.swing.JPanel buildTotalsPanel() {
        javax.swing.JPanel totalsPanel = new javax.swing.JPanel(new java.awt.GridLayout(4, 2, 0, 0));
        totalsPanel.setOpaque(false);
        totalsPanel.setMaximumSize(new java.awt.Dimension(220, 96));
        totalsPanel.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.DARK_GRAY),
            javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0)
        ));

        totalsPanel.add(createTotalsCell("Subtotal", true));
        totalsPanel.add(createTotalsCell(stripCurrency(jLabel19.getText()), false));
        totalsPanel.add(createTotalsCell("Discount", true));
        totalsPanel.add(createTotalsCell(stripCurrency(jLabel25.getText()), false));
        totalsPanel.add(createTotalsCell("VAT @ 20%", true));
        totalsPanel.add(createTotalsCell(stripCurrency(jLabel21.getText()), false));
        totalsPanel.add(createTotalsCell("Amount Due", true));
        totalsPanel.add(createTotalsCell(stripCurrency(jLabel22.getText()), false));

        javax.swing.JPanel wrapper = new javax.swing.JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 0, 0));
        wrapper.setOpaque(false);
        wrapper.add(totalsPanel);
        return wrapper;
    }

    private javax.swing.JLabel createTotalsCell(String text, boolean leftAligned) {
        javax.swing.JLabel label = new javax.swing.JLabel(text);
        label.setFont(new java.awt.Font("Serif", java.awt.Font.PLAIN, 13));
        label.setOpaque(true);
        label.setBackground(java.awt.Color.WHITE);
        label.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(java.awt.Color.DARK_GRAY),
            javax.swing.BorderFactory.createEmptyBorder(4, 8, 4, 8)
        ));
        label.setHorizontalAlignment(leftAligned
            ? javax.swing.SwingConstants.LEFT
            : javax.swing.SwingConstants.RIGHT);
        return label;
    }

    private String stripCurrency(String value) {
        return value.replace("£", "").replace("Â£", "").replace("Ã‚Â£", "").trim();
    }

    private void updateAccountIdVisibility() {
        boolean isAccountHolder = "Account Holder".equals(String.valueOf(jComboBox2.getSelectedItem()));
        jLabel11.setVisible(isAccountHolder);
        jTextField2.setVisible(isAccountHolder);
        if (!isAccountHolder) {
            jTextField2.setText("");
        }
        updatePaymentMethodOptions();
        revalidate();
        repaint();
    }

    private void updatePaymentMethodOptions() {
        boolean isAccountHolder = "Account Holder".equals(String.valueOf(jComboBox2.getSelectedItem()));
        String previousSelection = String.valueOf(jComboBox5.getSelectedItem());

        if (isAccountHolder) {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                "Cash", "Card", "Credit"
            }));
        } else {
            jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
                "Cash", "Card"
            }));
        }

        if (previousSelection != null) {
            for (int i = 0; i < jComboBox5.getItemCount(); i++) {
                if (previousSelection.equals(jComboBox5.getItemAt(i))) {
                    jComboBox5.setSelectedItem(previousSelection);
                    return;
                }
            }
        }

        jComboBox5.setSelectedIndex(0);
    }

    private void handlePaymentMethodSelection() {
        if ("Card".equals(String.valueOf(jComboBox5.getSelectedItem()))) {
            if (!captureCardDetails()) {
                jComboBox5.setSelectedItem("Cash");
            }
        } else {
            cardDetailsCaptured = false;
            cardSummary = "";
        }
    }

    private boolean captureCardDetails() {
        javax.swing.JTextField cardholderField = new javax.swing.JTextField();
        javax.swing.JTextField cardNumberField = new javax.swing.JTextField();
        javax.swing.JTextField expiryField = new javax.swing.JTextField();

        javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));
        panel.add(new javax.swing.JLabel("Cardholder Name:"));
        panel.add(cardholderField);
        panel.add(new javax.swing.JLabel("Card Number:"));
        panel.add(cardNumberField);
        panel.add(new javax.swing.JLabel("Expiry (MM/YY):"));
        panel.add(expiryField);

        int result = javax.swing.JOptionPane.showConfirmDialog(
            this,
            panel,
            "Enter Card Details",
            javax.swing.JOptionPane.OK_CANCEL_OPTION,
            javax.swing.JOptionPane.PLAIN_MESSAGE
        );

        if (result != javax.swing.JOptionPane.OK_OPTION) {
            return false;
        }

        String cardholder = cardholderField.getText().trim();
        String cardNumber = cardNumberField.getText().replaceAll("\\s+", "");
        String expiry = expiryField.getText().trim();

        if (cardholder.isEmpty() || expiry.isEmpty() || !cardNumber.matches("\\d{4,16}")) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Enter valid card details. Use digits only for the card number."
            );
            return false;
        }

        String lastFour = cardNumber.substring(cardNumber.length() - 4);
        cardDetailsCaptured = true;
        cardSummary = "ending " + lastFour;
        cardNumberForBackend = cardNumber;
        cardExpiryForBackend = expiry;
        return true;
    }

    private String formatCurrency(double value) {
        return String.format("£%.2f", value);
    }

    private double parseCurrency(String value) {
        return Double.parseDouble(value.replace("£", "").trim());
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
