/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package GUI;

/**
 *
 * @author laraashour
 */

import stock.CA_Stock_API_Impl;
import database.DBConnection;
import java.sql.Connection;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.RowFilter;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

public class Stock extends javax.swing.JPanel {
    private javax.swing.table.TableRowSorter<javax.swing.table.DefaultTableModel> sorter;
    private CA_Stock_API_Impl stockApi;
    private Connection conn;
    
    public Stock() {
    initComponents();
    
 try {
    conn = DBConnection.getConnection();

    if (conn == null) {
        JOptionPane.showMessageDialog(this, "Database connection failed.");
        return;
    }

    stockApi = new CA_Stock_API_Impl(conn);
} catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Database connection failed: " + e.getMessage());
    e.printStackTrace();
    return;
}

    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // remove dummy rows

    sorter = new TableRowSorter<>(model);
    jTable1.setRowSorter(sorter);

    setupSearchFilter();

    txtLowStock.setEditable(false);
    txtLowStock.setFocusable(false);
    txtLowStock.setHighlighter(null);
    txtLowStock.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

    txtLowStock.setOpaque(true);
    txtLowStock.setBackground(new java.awt.Color(242, 203, 121));
    txtLowStock.setBorder(null);
    txtLowStock.setLineWrap(true);
    txtLowStock.setWrapStyleWord(true);

    jScrollPane2.setBorder(null);
    jScrollPane2.setOpaque(true);
    jScrollPane2.setBackground(new java.awt.Color(242, 203, 121));
    jScrollPane2.getViewport().setOpaque(true);
    jScrollPane2.getViewport().setBackground(new java.awt.Color(242, 203, 121));

    jTable1.getTableHeader().setFont(new java.awt.Font("Helvetica Neue", java.awt.Font.BOLD, 14));
    jTable1.getTableHeader().setForeground(new java.awt.Color(0, 102, 204));
    jTable1.getTableHeader().repaint();

    loadStockTable();
    updateLowStockAlertFromBackend();

}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitle = new javax.swing.JLabel();
        lbInfo1 = new javax.swing.JLabel();
        alertPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLowStock = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        lbTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        lbTitle.setText("Stock Management ");

        lbInfo1.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lbInfo1.setForeground(new java.awt.Color(102, 102, 102));
        lbInfo1.setText("Manage your pharmacy inventory");

        alertPanel1.setBackground(new java.awt.Color(242, 203, 121));
        alertPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtLowStock.setBackground(new java.awt.Color(240, 203, 121));
        txtLowStock.setColumns(20);
        txtLowStock.setRows(5);
        txtLowStock.setBorder(null);
        jScrollPane2.setViewportView(txtLowStock);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 17, 0));
        jLabel2.setText("Low Stock Alert");

        javax.swing.GroupLayout alertPanel1Layout = new javax.swing.GroupLayout(alertPanel1);
        alertPanel1.setLayout(alertPanel1Layout);
        alertPanel1Layout.setHorizontalGroup(
            alertPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(alertPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(alertPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        alertPanel1Layout.setVerticalGroup(
            alertPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, alertPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Search:");

        jTextField1.setText("Search by name or product ID...");
        jTextField1.setSelectionColor(new java.awt.Color(153, 153, 153));
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jScrollPane1.setForeground(new java.awt.Color(0, 0, 51));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Quantity", "Low Bound", "Price", "Product Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setBackground(new java.awt.Color(0, 0, 51));
        jButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("+ Add Item");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setBackground(new java.awt.Color(0, 0, 51));
        jButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update Quantity");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setBackground(new java.awt.Color(0, 0, 51));
        jButton3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("- Remove Item");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setBackground(new java.awt.Color(0, 0, 51));
        jButton4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Record Delivery");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alertPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTitle)
                    .addComponent(lbInfo1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lbTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInfo1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alertPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

    }//GEN-LAST:event_jTextField1ActionPerformed

    private void setupSearchFilter() {
    jTextField1.getDocument().addDocumentListener(new DocumentListener() {
        private void filter() {
            String text = jTextField1.getText().trim();

            if (text.isEmpty() || text.equalsIgnoreCase("Search by name or product ID...")) {
                sorter.setRowFilter(null);
            } else {
                sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(text), 0, 1));
            }
        }

        @Override
        public void insertUpdate(DocumentEvent e) {
            filter();
        }

        @Override
        public void removeUpdate(DocumentEvent e) {
            filter();
        }

        @Override
        public void changedUpdate(DocumentEvent e) {
            filter();
        }
    });
}
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    javax.swing.JTextField txtProductId = new javax.swing.JTextField();
    javax.swing.JTextField txtName = new javax.swing.JTextField();
    javax.swing.JTextField txtPrice = new javax.swing.JTextField();
    javax.swing.JTextField txtVatRate = new javax.swing.JTextField();
    javax.swing.JTextField txtProductType = new javax.swing.JTextField();
    javax.swing.JTextField txtDescription = new javax.swing.JTextField();
    javax.swing.JTextField txtQuantity = new javax.swing.JTextField();
    javax.swing.JTextField txtLowBound = new javax.swing.JTextField();

    javax.swing.JPanel panel = new javax.swing.JPanel(new java.awt.GridLayout(0, 1, 5, 5));
    panel.add(new javax.swing.JLabel("Product ID:"));
    panel.add(txtProductId);
    panel.add(new javax.swing.JLabel("Name:"));
    panel.add(txtName);
    panel.add(new javax.swing.JLabel("Price:"));
    panel.add(txtPrice);
    panel.add(new javax.swing.JLabel("VAT Rate:"));
    panel.add(txtVatRate);
    panel.add(new javax.swing.JLabel("Product Type:"));
    panel.add(txtProductType);
    panel.add(new javax.swing.JLabel("Description:"));
    panel.add(txtDescription);
    panel.add(new javax.swing.JLabel("Quantity:"));
    panel.add(txtQuantity);
    panel.add(new javax.swing.JLabel("Low Bound:"));
    panel.add(txtLowBound);

    int result = JOptionPane.showConfirmDialog(
        this,
        panel,
        "Add New Stock Item",
        JOptionPane.OK_CANCEL_OPTION,
        JOptionPane.PLAIN_MESSAGE
    );

    if (result != JOptionPane.OK_OPTION) {
        return;
    }

    try {
        int productId = Integer.parseInt(txtProductId.getText().trim());
        String productName = txtName.getText().trim();
        double price = Double.parseDouble(txtPrice.getText().trim());
        double vatRate = Double.parseDouble(txtVatRate.getText().trim());
        String productType = txtProductType.getText().trim();
        String description = txtDescription.getText().trim();
        int quantity = Integer.parseInt(txtQuantity.getText().trim());
        int lowBound = Integer.parseInt(txtLowBound.getText().trim());
        
         // CHECK IF PRODUCT ALREADY EXISTS
    if (stockApi.productExists(productId)) {
        JOptionPane.showMessageDialog(this, "Product ID already exists. Please use a different ID.");
        return;
    }

        if (productName.isEmpty() || productType.isEmpty() || description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.");
            return;
        }

        if (price < 0 || vatRate < 0 || quantity < 0 || lowBound < 0) {
            JOptionPane.showMessageDialog(this, "Numeric values must be 0 or greater.");
            return;
        }

        boolean success = stockApi.addNewProductWithStock(
            productId, productName, price, vatRate, productType, description, quantity, lowBound
        );

        if (success) {
            JOptionPane.showMessageDialog(this, "New stock item added successfully.");
            loadStockTable();
            updateLowStockAlertFromBackend();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to add new stock item.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter valid numeric values.");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a stock item to remove.");
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to delete this stock item?",
        "Confirm Delete",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm != JOptionPane.YES_OPTION) {
        return;
    }

    int modelRow = jTable1.convertRowIndexToModel(selectedRow);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int productId = Integer.parseInt(model.getValueAt(modelRow, 0).toString());

    boolean success = stockApi.removeStock(productId);

    if (success) {
        JOptionPane.showMessageDialog(this, "Stock item removed successfully.");
        loadStockTable();
        updateLowStockAlertFromBackend();
    } else {
        JOptionPane.showMessageDialog(this, "Failed to remove stock item.");
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a stock item first.");
        return;
    }

    int modelRow = jTable1.convertRowIndexToModel(selectedRow);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    int productId = Integer.parseInt(model.getValueAt(modelRow, 0).toString());

    String newQuantityText = JOptionPane.showInputDialog(this, "Enter new quantity:");

    if (newQuantityText == null) return;

    try {
        int newQuantity = Integer.parseInt(newQuantityText.trim());

        if (newQuantity < 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be 0 or greater.");
            return;
        }

        boolean success = stockApi.updateStockQuantity(productId, newQuantity);

        if (success) {
            JOptionPane.showMessageDialog(this, "Stock quantity updated successfully.");
            loadStockTable();
            updateLowStockAlertFromBackend();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to update stock quantity.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Please enter a valid whole number.");
    }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Please select a product to record delivery.");
        return;
    }

    int modelRow = jTable1.convertRowIndexToModel(selectedRow);
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int productId = Integer.parseInt(model.getValueAt(modelRow, 0).toString());

    String input = JOptionPane.showInputDialog(this, "Enter delivered quantity:");

    if (input == null) return;

    try {
        int deliveredQty = Integer.parseInt(input.trim());

        if (deliveredQty <= 0) {
            JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.");
            return;
        }

        boolean success = stockApi.recordDelivery(productId, deliveredQty);

        if (success) {
            JOptionPane.showMessageDialog(this, "Delivery recorded successfully.");
            loadStockTable();
            updateLowStockAlertFromBackend();
        } else {
            JOptionPane.showMessageDialog(this, "Failed to record delivery.");
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Invalid quantity.");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

private void updateLowStockAlertFromBackend() {
    if (stockApi == null) {
        txtLowStock.setText("Unable to load low stock alerts.");
        return;
    }

    java.util.List<String> lowStockItems = stockApi.getLowStockItems();

    if (lowStockItems.isEmpty()) {
        txtLowStock.setText("No low stock items");
    } else {
        StringBuilder sb = new StringBuilder();
        sb.append("Low Stock (").append(lowStockItems.size()).append(" items)\n\n");

        for (String item : lowStockItems) {
            sb.append("• ").append(item).append("\n\n");
        }

        txtLowStock.setText(sb.toString());
    }
}

private void loadStockTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);

    if (stockApi == null) {
        return;
    }

    List<Object[]> items = stockApi.getAllStockItems();

    for (Object[] row : items) {
        model.addRow(row);
    }
}
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel alertPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbInfo1;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JTextArea txtLowStock;
    // End of variables declaration//GEN-END:variables
}
